# Site settings
title: Wenshan's Website
email: shanshan1370@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Wenshan's website. 
  You can find her latest research interests and some drivels as well.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wangwenshan.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Amigoshan
favicon: "image/ico_brain.ico"
me-img: "image/happy.jpg"
# Build settings
markdown: kramdown


comments: true
#disqus-shortname: "wenshan"
duoshuo-shortname: "wenshan"

cnzz_tongji:
  enable: true
  siteid: 1260335202

