# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'jekyll', '~> 3.3'

# **or** if you're deploying via GitHub Pages
gem 'github-pages'

# gem "rails"
